### ISSUE TITLE
Improve rendering

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/rbmhtechnology.github.io#10]
Reference: http://rbmhtechnology.github.io/operation-based-crdt-framework/
- syntax highlighting for `{% highlight scala %}` should be similar to syntax highlighting for 
  
  ``````
  ```scala
  ...
  
  ```
  ``````
  
  on Github.
- code should be clipped when exceeding code area width (and a horizontal scroll bar should be added instead).
- text pre-formatted with ``...`` should have different color than normal text.

**Comment by purthaler** [comment]
not needed any more
